0.2.a
> Game Latest Release version
- File Name
File Import
File Directory
File Location
File Download Location
File Download URL
Count
_______________________________________________________
- Characters
true
Unfinished Undefined/Game/
Unfinished Undefined/Game/Cヾ(￣▽￣)
Unfinished Undefined/_Downloaded/Characters.zip
http://bit.ly/UndefinedCharacters
- GLOBAL
true
Unfinished Undefined/Game/
Unfinished Undefined/Game/LG(✿◡‿◡)
Unfinished Undefined/_Downloaded/Global.zip
http://bit.ly/UndefinedGlobal
- OST
true
Unfinished Undefined/Resources/
Unfinished Undefined/Resources/ヾ(⌐■_■)ノ♪
Unfinished Undefined/_Downloaded/OST.zip
http://bit.ly/UndefinedOST
- SFX
true
Unfinished Undefined/Resources/
Unfinished Undefined/Resources/♪(´▽｀)
Unfinished Undefined/_Downloaded/SFX.zip
http://bit.ly/UndefinedSFX
- UI
true
Unfinished Undefined/Game/
Unfinished Undefined/Game/ᓚᘏᗢ
Unfinished Undefined/_Downloaded/UI.zip
http://bit.ly/UndefinedUI
